### ISSUE TITLE
Hi! Please, help me, i can't use this mode on 1.19.3, he doesn't work

### ISSUE THREAD

**Issue by Merbuz** [LXYan2333/Fabric-Bedrock-Miner#60]

**Comment by Bunnui** [comment]
This is because the Minecraft in 1.19.3
net.Minecraft.Tag.FluidTags changes have taken place in the class path

https://github.com/LXYan2333/Fabric-Bedrock-Miner/blob/35339842c243c01ced12422795cc99fb8681777f/src/main/java/yan/lx/bedrockminer/utils/InventoryManager.java#L18

https://github.com/Bunnui/Fabric-Bedrock-Miner/blob/0eac0fa3b9dcd1c7ab1d11e2f4508b1664e8119a/src/main/java/yan/lx/bedrockminer/utils/InventoryManager.java#L20

This is the branch of my Fork modification: https://github.com/Bunnui/Fabric-Bedrock-Miner

Download address: [releases](https://github.com/Bunnui/Fabric-Bedrock-Miner/releases)

**Comment by Merbuz** [comment]
thanks! :D
